name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: danteev/texlive:latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build the Thesis
      run: make
    - uses: actions/upload-artifact@master
      with:
        name: Compiled Thesis
        path: ./thesis.pdf
